CXX = g++
CFLAGS = -Wall -g

binary_tree_level_order_traversal: binary_tree_level_order_traversal.cpp
	$(CXX) $(CFLAGS) -o $@ $^

binary_tree_level_order_traversal_bfs: binary_tree_level_order_traversal_bfs.cpp
	$(CXX) $(CFLAGS) -o $@ $^

binary_tree_level_order_traversal_dfs: binary_tree_level_order_traversal_dfs.cpp
	$(CXX) $(CFLAGS) -o $@ $^