CXX=g++
CFLAGS = -Wall -g

bfs: bfs.cpp
	$(CXX) $(CFLAGS) -o $@ $^

duplicate_array: duplicate_array.cpp
	$(CXX) $(CFLAGS) -o $@ $^

prime_number: prime_number.cpp
	$(CXX) $(CFLAGS) -o $@ $^

sin_calculus: sin_calculus.cpp
	$(CXX) $(CFLAGS) -o $@ $^
