CXX=g++
CFLAGS = -Wall -g

validate_binary_search_tree_in_order: validate_binary_search_tree_in_order.cpp
	$(CXX) $(CFLAGS) -o $@ $^

validate_binary_search_tree: validate_binary_search_tree.cpp
	$(CXX) $(CFLAGS) -o $@ $^
