CXX=g++
CFLAGS = -Wall -g

add_two_numbers: add_two_numbers.cpp
	$(CXX) $(CFLAGS) -o $@ $^

bulls_and_cows: bulls_and_cows.cpp
	$(CXX) $(CFLAGS) -o $@ $^

two_sum: two_sum.cpp
	$(CXX) $(CFLAGS) -o $@ $^

validate_binary_search_tree_in_order: validate_binary_search_tree_in_order.cpp
	$(CXX) $(CFLAGS) -o $@ $^

validate_binary_search_tree: validate_binary_search_tree.cpp
	$(CXX) $(CFLAGS) -o $@ $^
