CXX = g++
CFLAGS = -Wall -g

add_two_numbers: add_two_numbers.cpp
	$(CXX) $(CFLAGS) -o $@ $^

bulls_and_cows: bulls_and_cows.cpp
	$(CXX) $(CFLAGS) -o $@ $^

count_number_of_maximum_bitwise_or_subsets: count_number_of_maximum_bitwise_or_subsets.cpp
	$(CXX) $(CFLAGS) -o $@ $^

longest_subarray_with_maximum_bitwise_and: longest_subarray_with_maximum_bitwise_and.cpp
	$(CXX) $(CFLAGS) -o $@ $^

subsets: subsets.cpp
	$(CXX) $(CFLAGS) -o $@ $^

two_sum: two_sum.cpp
	$(CXX) $(CFLAGS) -o $@ $^