CXX=g++
CFLAGS = -Wall -g

add_two_numbers: add_two_numbers.cpp
	$(CXX) $(CFLAGS) -o $@ $^

bulls_and_cows: bulls_and_cows.cpp
	$(CXX) $(CFLAGS) -o $@ $^

two_sum: two_sum.cpp
	$(CXX) $(CFLAGS) -o $@ $^