CXX=g++
CFLAGS = -Wall -g

constructor_test: constructor_test.cpp
	$(CXX) $(CFLAGS) -o $@ $^

duplicate_array: duplicate_array.cpp
	$(CXX) $(CFLAGS) -o $@ $^

n_queen_count: n_queen_count.cpp
	$(CXX) $(CFLAGS) -o $@ $^

prime_number: prime_number.cpp
	$(CXX) $(CFLAGS) -o $@ $^

sin_calculus: sin_calculus.cpp
	$(CXX) $(CFLAGS) -o $@ $^
